name: flutter_modular_navigation

packages:
  - .
  - apps/**
  - core/**
  - feature/**

sdkPath: .fvm/flutter_sdk

scripts:
  # ==================================================================================================
  # build & rebuild
  # ==================================================================================================

  build:
    run: melos bs && melos get && melos br

  rebuild:
    run: melos cln && melos bs && melos get && melos br

  # ==================================================================================================
  # pub get & pub run build_runner build &
  # ==================================================================================================

  get:
    run: flutter pub get
    description: flutter pub get
    exec:
      concurrency: 10

  br:
    run: melos exec -c 10 --depends-on="build_runner" -- flutter pub run build_runner build --delete-conflicting-outputs
    description: flutter pub run build_runner build

  cln:
    run: flutter clean
    description: flutter clean
    exec:
      concurrency: 10

  up:
    run: flutter pub upgrade
    description: flutter pub upgrade
    exec:
      concurrency: 10