name: flutter_modular_navigation

packages:
  - .
  - apps/**
  - core/**
  - feature/**

sdkPath: .fvm/flutter_sdk

scripts:
  # ==================================================================================================
  # build & rebuild
  # ==================================================================================================



  # ==================================================================================================
  # pub get & pub run build_runner build &
  # ==================================================================================================

  sync:
    run: melos bs
    description: flutter pub get

  sync_cr:
    run: melos bs
    description: flutter pub get (choose & run)
    packageFilters:
      flutter: true

  br:
    run: melos exec -c 30 --depends-on="build_runner" -- flutter pub run build_runner build --delete-conflicting-outputs
    description: flutter pub run build_runner build

  br_cr:
    run: melos exec -c 30 --depends-on="build_runner" -- flutter pub run build_runner build --delete-conflicting-outputs
    description: flutter pub run build_runner build (choose & run)
    packageFilters:
      depends-on: "build_runner"

  up:
    run: melos exec -c 30 -- flutter pub upgrade
    description: flutter pub upgrade

  up_cr:
    run: melos exec -c 30 -- flutter pub upgrade
    description: flutter pub upgrade (choose & run)
    packageFilters:
      flutter: true

  cln:
    run: |
      melos exec -c 30 -- flutter clean && \
      melos exec -- find . -name '*.lock' -delete && \
      melos exec -- find . -name '*overrides.yaml' -delete && \
      melos exec -- find . -name '*.config.dart' -delete
    description: flutter clean