name: flutter_modular_navigation
description: Flutter Modular Navigation
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  app:
    path: apps/app
  root:
    path: feature/root
  home:
    path: feature/home
  nav_direction:
    path: feature/common/nav_direction
  navigation:
    path: core/navigation
  di_injector:
    path: apps/di_injector

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  injectable: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  melos: 3.1.0
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true