name: feature_b
description: Feature B
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  di_injector:
    path: ../../di_injector
  navigation:
    path: ../../navigation

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  injectable: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true