name: app
description: App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  di_injector:
    path: ../di_injector
  root:
    path: ../../feature/root
  home:
    path: ../../feature/home
  nav_direction:
    path: ../../feature/common/nav_direction
  navigation:
    path: ../../core/navigation

  cupertino_icons: ^1.0.5
  go_router: ^10.1.0
  get_it: ^7.6.0
  injectable: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0

flutter:
  uses-material-design: true